# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 21:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('envelopes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Envelope Identifier')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created', models.DateTimeField(blank=True)),
                ('modified', models.DateTimeField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelopes', to='envelopes.Account')),
                ('creator', models.ForeignKey(help_text='User who created the envelope.', on_delete=django.db.models.deletion.PROTECT, related_name='envelopes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('friendly_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('created', models.DateTimeField(blank=True)),
                ('type', models.CharField(choices=[('CREATED', 'Created'), ('DEPOSITED', 'Deposited'), ('WITHDRAWN', 'Withdrawn')], max_length=30)),
                ('delta', models.DecimalField(decimal_places=2, help_text='Balance delta', max_digits=14)),
                ('description', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='envelopes.Category')),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='envelopes.Envelope')),
                ('user', models.ForeignKey(help_text='User who performed the action.', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
