#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
  export PREFIX-"venv/bin/"
fi

set -x

${PREFIX}flake8 envelopes config tests
${PREFIX}isort envelopes tests --recursive --check-only
${PREFIX}mypy envelopes --ignore-missing-imports
